name: "shared-library"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api
    restart: always
    # i put this limit so that it mimics how the app would work in an EC2 free tier instance :D
    mem_limit: 1g
    cpus: 0.5
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - library-network
    command: >
      sh -c "
        yarn prisma migrate deploy &&
        node dist/main
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
